-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.delitos
(
    delito_id serial NOT NULL,
    codigo character varying(10) COLLATE pg_catalog."default" NOT NULL,
    nombre character varying(255) COLLATE pg_catalog."default" NOT NULL,
    descripcion character varying(255) COLLATE pg_catalog."default",
    oculto boolean NOT NULL,
    CONSTRAINT delitos_pkey PRIMARY KEY (delito_id),
    CONSTRAINT delitos_codigo_key UNIQUE (codigo)
);

CREATE TABLE IF NOT EXISTS public.detalle_detenciones
(
    detalledetencion_id serial NOT NULL,
    fecha_ingreso date NOT NULL,
    descripcion text COLLATE pg_catalog."default" NOT NULL,
    lugar character varying(45) COLLATE pg_catalog."default",
    direccion_idfk integer NOT NULL,
    detencion_idfk integer NOT NULL,
    CONSTRAINT detalle_detenciones_pkey PRIMARY KEY (detalledetencion_id)
);

CREATE TABLE IF NOT EXISTS public.detalle_detenidos
(
    detalle_detenido_id serial NOT NULL,
    primer_nombre character varying(255) COLLATE pg_catalog."default" NOT NULL,
    segundo_nombre character varying(255) COLLATE pg_catalog."default",
    primer_apellido character varying(255) COLLATE pg_catalog."default" NOT NULL,
    segundo_apellido character varying(255) COLLATE pg_catalog."default",
    fecha_nacimiento date NOT NULL,
    edad integer NOT NULL,
    sexo character varying(10) COLLATE pg_catalog."default" NOT NULL,
    nombre_foto character varying(255) COLLATE pg_catalog."default",
    ruta_foto character varying(255) COLLATE pg_catalog."default",
    estado_civil character varying(50) COLLATE pg_catalog."default",
    detenido_idfk integer NOT NULL,
    direccion_idfk integer NOT NULL,
    CONSTRAINT detalle_detenidos_pkey PRIMARY KEY (detalle_detenido_id)
);

CREATE TABLE IF NOT EXISTS public.detenciones
(
    detencion_id serial NOT NULL,
    numero character varying(40) COLLATE pg_catalog."default" NOT NULL,
    estatus character varying(20) COLLATE pg_catalog."default" NOT NULL,
    oculto boolean NOT NULL,
    organismo_idfk integer NOT NULL,
    delito_idfk integer NOT NULL,
    detenido_idfk integer NOT NULL,
    CONSTRAINT detenciones_pkey PRIMARY KEY (detencion_id),
    CONSTRAINT detenciones_numero_key UNIQUE (numero)
);

CREATE TABLE IF NOT EXISTS public.detenidos
(
    detenido_id serial NOT NULL,
    cedula character varying(20) COLLATE pg_catalog."default" NOT NULL,
    ciudadano_idfk integer NOT NULL,
    oculto boolean NOT NULL,
    CONSTRAINT detenidos_pkey PRIMARY KEY (detenido_id),
    CONSTRAINT detenidos_cedula_key UNIQUE (cedula)
);

CREATE TABLE IF NOT EXISTS public.direcciones
(
    direccion_id serial NOT NULL,
    estado character varying(255) COLLATE pg_catalog."default" NOT NULL,
    municipio character varying(255) COLLATE pg_catalog."default" NOT NULL,
    direccion character varying(255) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT direcciones_pkey PRIMARY KEY (direccion_id)
);

CREATE TABLE IF NOT EXISTS public.egreso_detenciones
(
    egreso_id serial NOT NULL,
    fecha_egreso date NOT NULL,
    descripcion text COLLATE pg_catalog."default" NOT NULL,
    tipoegreso_idfk integer NOT NULL,
    detencion_idfk integer NOT NULL,
    CONSTRAINT egreso_detenciones_pkey PRIMARY KEY (egreso_id)
);

CREATE TABLE IF NOT EXISTS public.estados
(
    estado_id serial NOT NULL,
    estado character varying(255) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT estados_pkey PRIMARY KEY (estado_id)
);

CREATE TABLE IF NOT EXISTS public.municipios
(
    municipio_id serial NOT NULL,
    municipio character varying(255) COLLATE pg_catalog."default" NOT NULL,
    estado_idfk integer NOT NULL,
    CONSTRAINT municipios_pkey PRIMARY KEY (municipio_id)
);

CREATE TABLE IF NOT EXISTS public.organismos
(
    organismo_id serial NOT NULL,
    codigo character varying(45) COLLATE pg_catalog."default" NOT NULL,
    nombre character varying(45) COLLATE pg_catalog."default" NOT NULL,
    descripcion text COLLATE pg_catalog."default" NOT NULL,
    telefono character varying(45) COLLATE pg_catalog."default" NOT NULL,
    correo character varying(45) COLLATE pg_catalog."default" NOT NULL,
    direccion_idfk integer NOT NULL,
    oculto boolean NOT NULL,
    CONSTRAINT organismos_pkey PRIMARY KEY (organismo_id),
    CONSTRAINT organismos_codigo_key UNIQUE (codigo)
);

CREATE TABLE IF NOT EXISTS public.roles
(
    rol_id serial NOT NULL,
    nombre_rol character varying(80) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT roles_pkey PRIMARY KEY (rol_id),
    CONSTRAINT roles_nombre_rol_key UNIQUE (nombre_rol)
);

CREATE TABLE IF NOT EXISTS public.tipo_egresos
(
    tipoegreso_id serial NOT NULL,
    nombre character varying(255) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT tipo_egresos_pkey PRIMARY KEY (tipoegreso_id)
);

CREATE TABLE IF NOT EXISTS public.usuarios
(
    usuario_id serial NOT NULL,
    nombre character varying(80) COLLATE pg_catalog."default" NOT NULL,
    apellido character varying(80) COLLATE pg_catalog."default" NOT NULL,
    correo character varying(80) COLLATE pg_catalog."default" NOT NULL,
    usuario character varying(80) COLLATE pg_catalog."default" NOT NULL,
    clave character varying(256) COLLATE pg_catalog."default" NOT NULL,
    rol_idfk integer NOT NULL,
    oculto boolean NOT NULL,
    CONSTRAINT usuarios_pkey PRIMARY KEY (usuario_id),
    CONSTRAINT usuarios_usuario_key UNIQUE (usuario)
);

ALTER TABLE IF EXISTS public.detalle_detenciones
    ADD CONSTRAINT detalle_detenciones_detencion_idfk_fkey FOREIGN KEY (detencion_idfk)
    REFERENCES public.detenciones (detencion_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.detalle_detenciones
    ADD CONSTRAINT detalle_detenciones_direccion_idfk_fkey FOREIGN KEY (direccion_idfk)
    REFERENCES public.direcciones (direccion_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.detalle_detenidos
    ADD CONSTRAINT detalle_detenidos_detenido_idfk_fkey FOREIGN KEY (detenido_idfk)
    REFERENCES public.detenidos (detenido_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.detalle_detenidos
    ADD CONSTRAINT detalle_detenidos_direccion_idfk_fkey FOREIGN KEY (direccion_idfk)
    REFERENCES public.direcciones (direccion_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.detenciones
    ADD CONSTRAINT detenciones_delito_idfk_fkey FOREIGN KEY (delito_idfk)
    REFERENCES public.delitos (delito_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.detenciones
    ADD CONSTRAINT detenciones_detenido_idfk_fkey FOREIGN KEY (detenido_idfk)
    REFERENCES public.detenidos (detenido_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.detenciones
    ADD CONSTRAINT detenciones_organismo_idfk_fkey FOREIGN KEY (organismo_idfk)
    REFERENCES public.organismos (organismo_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.egreso_detenciones
    ADD CONSTRAINT egreso_detenciones_detencion_idfk_fkey FOREIGN KEY (detencion_idfk)
    REFERENCES public.detenciones (detencion_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.egreso_detenciones
    ADD CONSTRAINT egreso_detenciones_tipoegreso_idfk_fkey FOREIGN KEY (tipoegreso_idfk)
    REFERENCES public.tipo_egresos (tipoegreso_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.municipios
    ADD CONSTRAINT municipios_estado_idfk_fkey FOREIGN KEY (estado_idfk)
    REFERENCES public.estados (estado_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.organismos
    ADD CONSTRAINT organismos_direccion_idfk_fkey FOREIGN KEY (direccion_idfk)
    REFERENCES public.direcciones (direccion_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.usuarios
    ADD CONSTRAINT usuarios_rol_idfk_fkey FOREIGN KEY (rol_idfk)
    REFERENCES public.roles (rol_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

END;